# $Id$

################################################################################

REGLOOKUP=$(BUILD_BIN)/reglookup
FILES=$(REGLOOKUP)

all: $(FILES)

$(REGLOOKUP): reglookup.c
	$(CC) $(OPTS) -o $@ reglookup.c
